85 docs diagrama de comunicaçãoelaboração
UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon pull request #99
Opened 2023-10-06 22:55 UTC by guilherme-puida

2023-10-08 22:40 UTC, ArthurFerreiraRodrigues requested changes

2023-10-08 22:40 UTC, ArthurFerreiraRodrigues commented on docs/Modelagem/Diagrama_de_Comunicação_Colaboração/Comunicação.md
> +ADICIONAR METODOLOGIA DEPOIS
Está pendente a seção de metodologia.

2023-10-08 23:30 UTC, guilherme-puida commented on docs/Modelagem/Diagrama_de_Comunicação_Colaboração/Comunicação.md
> +ADICIONAR METODOLOGIA DEPOIS
adicionado

2023-10-09 00:40 UTC, ArthurFerreiraRodrigues approved these changes

2023-10-09 00:41 UTC, merged